"""empty message

Revision ID: a7ebc6eac964
Revises: d322fb53e354
Create Date: 2020-02-26 16:31:04.710744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7ebc6eac964'
down_revision = 'd322fb53e354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('_password', sa.String(length=128), nullable=True))
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('admin', '_password')
    # ### end Alembic commands ###
