"""empty message

Revision ID: d322fb53e354
Revises: 
Create Date: 2020-02-26 15:42:51.821635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd322fb53e354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_cc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_seven',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('post_journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_journal_timestamp'), 'post_journal', ['timestamp'], unique=False)
    op.create_table('post_life',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_life_timestamp'), 'post_life', ['timestamp'], unique=False)
    op.create_table('post_cc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('category_cc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_cc_id'], ['category_cc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_cc_timestamp'), 'post_cc', ['timestamp'], unique=False)
    op.create_table('post_seven',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('category_seven_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_seven_id'], ['category_seven.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_seven_timestamp'), 'post_seven', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_seven_timestamp'), table_name='post_seven')
    op.drop_table('post_seven')
    op.drop_index(op.f('ix_post_cc_timestamp'), table_name='post_cc')
    op.drop_table('post_cc')
    op.drop_index(op.f('ix_post_life_timestamp'), table_name='post_life')
    op.drop_table('post_life')
    op.drop_index(op.f('ix_post_journal_timestamp'), table_name='post_journal')
    op.drop_table('post_journal')
    op.drop_table('category_seven')
    op.drop_table('category_cc')
    op.drop_table('admin')
    # ### end Alembic commands ###
