"""empty message

Revision ID: dfa054fcb012
Revises: addd083b5b35
Create Date: 2020-03-03 22:08:28.285585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfa054fcb012'
down_revision = 'addd083b5b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_seven')
    op.add_column('album', sa.Column('filename_small', sa.String(length=64), nullable=True))
    op.add_column('photo', sa.Column('filename_small', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'filename_small')
    op.drop_column('album', 'filename_small')
    op.create_table('category_seven',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
