"""empty message

Revision ID: fd031ada696b
Revises: 70b94af4432c
Create Date: 2020-03-01 16:23:38.655784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd031ada696b'
down_revision = '70b94af4432c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vlog', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vlog', 'description')
    # ### end Alembic commands ###
